homepage: "https://github.com/HojoM/oss-fuzz-example"

main_repo: 'https://github.com/HojoM/oss-fuzz-example'

primary_contact: "aidenmax187@gmail.com"

auto_ccs :

  - "aidenmax187@gmail.com"

language: c
